server:
    port: 7002
spring:
    application:
        name: spike-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://121.37.154.99:3007/spike?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=no
        username: root
        password: zgt9321@jj.com
        type: com.alibaba.druid.pool.DruidDataSource
    data:
        redis:
            host: 121.37.154.99
            port: 6379
            database: 0
            lettuce:
                pool:
                    enabled: true
                    max-active: 100
                    max-idle: 20
                    min-idle: 5
            password: zgt123
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
rocketmq:
    name-server: 172.31.156.45:9876